#!/usr/bin/env bash
# Copyright 2026 Dominik Schlosser
# SPDX-License-Identifier: Apache-2.0
#
# The cut-over half of the migration demo (see docs/DEMO.md): stops the filestore instance,
# applies the CRs generated by scripts/migrate-filestore.sh and deploys Keycloak with k8store in
# the GitOps posture (read-only, valuesFrom references resolved on read). The database is left
# untouched - users, service accounts and sessions carry over.
#
# Usage: scripts/switch-to-k8store.sh [migrated-crs-dir]   (default: ./migrated-crs)
set -euo pipefail
cd "$(dirname "$0")/.."

KUBECTL="kubectl --context kind-k8store"

CRS_DIR=${1:-migrated-crs}
if [ ! -d "${CRS_DIR}" ]; then
  echo "No CR directory '${CRS_DIR}' - run scripts/migrate-filestore.sh first" >&2
  exit 1
fi

echo "Stopping the filestore instance..."
${KUBECTL} -n keycloak scale deployment/keycloak-filestore --replicas=0

echo "Applying CRDs and the migrated custom resources..."
${KUBECTL} apply --server-side -f crds/
${KUBECTL} -n keycloak apply -R -f "${CRS_DIR}/"

# deploy.sh waits for the rollout and smoke-checks the admin login; with a migrated master CR in
# place the read-only first boot works (the bootstrap only creates the admin user in the
# database - here it already exists, created by the filestore instance against the same postgres)
scripts/deploy.sh --read-only true --resolve-references true

# Migration-specific smoke check: the demo client must authenticate through k8store with the
# secret that only exists in the Kubernetes Secret, using its migrated service account.
echo "Smoke check: migrated demo client through k8store..."
${KUBECTL} -n keycloak port-forward svc/keycloak 18080:8080 >/dev/null 2>&1 &
PF_PID=$!
trap 'kill "${PF_PID}" 2>/dev/null || true' EXIT
sleep 3
SECRET_VALUE=$(${KUBECTL} -n keycloak get secret keycloak-demo-secrets -o jsonpath='{.data.CLIENT_SECRET}' | base64 -d)
GRANT=000
for _ in $(seq 1 30); do
  GRANT=$(curl -s -o /dev/null -w '%{http_code}' \
    -d 'client_id=web-app' -d "client_secret=${SECRET_VALUE}" -d 'grant_type=client_credentials' \
    http://localhost:18080/realms/demo/protocol/openid-connect/token || true)
  [ "${GRANT}" = "200" ] && break
  sleep 2
done
kill "${PF_PID}" 2>/dev/null || true
trap - EXIT
if [ "${GRANT}" != "200" ]; then
  echo "Smoke check FAILED: web-app client_credentials grant returned HTTP ${GRANT}" >&2
  exit 1
fi
echo "Smoke check OK: the migrated client authenticates through k8store"

cat <<'EOF'

Migration complete. Keycloak now serves the configuration from the custom resources in
the cluster (read-only), with secrets resolved from Kubernetes Secrets on read.
  kubectl -n keycloak get keycloakrealms,keycloakclients
  http://localhost:8080   # console (admin/admin) on the default kind cluster;
                          # otherwise: kubectl -n keycloak port-forward svc/keycloak 8080:8080
EOF
